title: 上树的CS学习资源站
favicon_ico: "/assets/images/favicon.ico"
remote_theme: pmarsceill/just-the-docs
compress_html:
  ignore:
    envs: all
  blanklines: true
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
color_scheme: dark
callouts:
  warning:
    title: 注意
    color: yellow
aux_links:
  "访问谷歌硬盘获取更多资源":
    - "https://drive.google.com/drive/folders/1y6jwn1JOWwHpGe560MKdPGGsYNJkBegz"
nav_external_links:
  - title: Algo2 双字幕视频课
    url: https://drive.google.com/drive/folders/1meCBv53Br-yNHnF8-SY9zf4AiRAXPTUj
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
  - title: CSA 双字幕视频课（更新中）
    url: https://drive.google.com/drive/folders/1mn-PaAuGoXsQ2klWw9dm9bkhSOuZA_57
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
  - title: PLC 中文版参考页（正在施工，即将开放）
    hide_icon: true # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false
  - title: Algo2 课程主页
    url: https://uob-cs-algorithms-ii.github.io/
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
  - title: CSA 课程主页
    url: https://uob-csa.github.io/website/
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
  - title: PLC reference 参考页
    url: https://uob-coms20007.github.io/reference/
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
