title: PL&C Reference
remote_theme: pmarsceill/just-the-docs
compress_html:
  ignore:
    envs: all
  blanklines: true
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
aux_links:
  "Unit Webpage":
    - "https://www.ole.bris.ac.uk/ultra/courses/_257216_1/cl/outline"
baseurl: /plc # place folder name if the site is served in a subfolder
